### ISSUE TITLE
Use Atom's own hyperlink recognition

### ISSUE THREAD

**Issue by timdp** [UziTech/hyperlink-hyperclick#3]
Came here from atom/link#6, obviously. :-)

As I mentioned there, Atom (at least mine) adds a `hyperlink` class to every hyperlink DOM element. Instead of using your own regexp to recognize links, couldn't you just get the DOM element under the cursor and check its class?

Not that I can come up with the code for that off the top of my head, but I imagine there's an API for it.

**Comment by timdp** [comment]
FYI: [Here's a discussion](https://discuss.atom.io/t/get-dom-element-under-cursor/20840/2) that suggests combining `TextEditorElement#pixelPositionForScreenPosition` with shadow DOM inspection but it looks like the former is deprecated.

**Comment by UziTech** [comment]
Yes, ideally this would be added to the [atom/link](https://github.com/atom/link/) package since they already go through the work of finding links but I just through this together.

I chose to use the [hyperclick](https://atom.io/packages/hyperclick) service so I didn't need to manage the mouse position or when ctrl/cmd is clicked
